[package]
name = "trawler"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[features]
cli = ["clap", "hyper", "url", "regex", "lazy_static"]
default = ["cli"]

[dependencies]
slog = "2.0.6"
slog-term = "2.0.1"
libc = "0.2"
rand = "0.4.0"
zipf = "1.0.0"
hdrhistogram = "6.0.0"

multiqueue = "0.3.2"
tokio-core = "0.1"
futures = "0.1"

clap = { version = "2.25.0", optional = true }
hyper = { version = "0.11", optional = true }
url = { version = "1.7", optional = true }
regex = { version = "0.2", optional = true }
lazy_static = { version = "1.0.0", optional = true }

[profile.release]
debug = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "trawler"
path = "src/bin/main.rs"
required-features = ["cli"]
